# Generated by Django 3.0.7 on 2020-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.CharField(choices=[('Ricardo', 'Ricardo'), ('Itala', 'Itala'), ('Thayssa', 'Thayssa')], default='Ricardo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='broker',
            field=models.CharField(choices=[('Ágora - Bradesco', 'Ágora - Bradesco'), ('Banco do Brasil', 'Banco do Brasil')], default='Banco do Brasil', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.CharField(choices=[('Ágora - Bradesco', 'Ágora - Bradesco'), ('Banco do Brasil', 'Banco do Brasil')], max_length=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(choices=[('Ricardo', 'Ricardo'), ('Itala', 'Itala'), ('Thayssa', 'Thayssa')], max_length=20),
        ),
    ]
