# Generated by Django 3.0.7 on 2020-07-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200630_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='buy_date',
            field=models.DateField(default='2020-01-20', verbose_name='Data de Compra'),
            preserve_default=False,
        ),
    ]
