# Generated by Django 3.0.7 on 2020-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wallet_buy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.CharField(choices=[('Ágora - Bradesco', 'Ágora - Bradesco'), ('Banco do Brasil', 'Banco do Brasil'), ('Itaú', 'Itaú')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.CharField(choices=[('Ricardo', 'Ricardo'), ('Itala', 'Itala'), ('Thayssa', 'Thayssa'), ('Caco', 'Caco')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='broker',
            field=models.CharField(choices=[('Ágora - Bradesco', 'Ágora - Bradesco'), ('Banco do Brasil', 'Banco do Brasil'), ('Itaú', 'Itaú')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(choices=[('Ricardo', 'Ricardo'), ('Itala', 'Itala'), ('Thayssa', 'Thayssa'), ('Caco', 'Caco')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('owner', 'stock', 'broker')},
        ),
    ]
